import { Poppins } from "next/font/google";

import './globals.css';

import type { Metadata } from 'next';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Specify required font weights
  variable: "--font-poppins", // Define a CSS variable for Tailwind
});

export const metadata: Metadata = {
  title: '  Admission Form',
  description: 'Generated by MGMU ERP Team',
  icons: '/LogoMGM.svg',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
